### ISSUE TITLE
Type of created project is wrong

### ISSUE THREAD

**Issue by mlabuda** [redhat-developer/che-starter#113]

**Comment by ibuziuk** [comment]
@mlabuda still have this issue

**Comment by ibuziuk** [comment]
@mlabuda well it should be actually `projectType` not `type`. Details here - https://issues.jboss.org/browse/CHE-133

**Comment by ibuziuk** [comment]
Should be fixed with - https://github.com/redhat-developer/che-starter/pull/124

**Comment by mlabuda** [comment]
Reopening. This is not fixed. Project does not have any key with name "projectType" as someone is thinking in the JIRA. By passing projectType key with a value you just pass a non-existing attribute of project and the real "type" value is set to blank.

That means, that we have blank type all the time - this issue is about that. And that is a serious problem. Red cross on a project means a problem - we could try to get workspace by a composite key through Che server API to find out what is the problem (there is an array of problems for a project in workspace json) and try to really fix the issue.

Having a blank type is a serious problem - if a project is blank and not maven, it cannot download dependencies, manage lifecycle. You also cannot run Unit tests. So this is a blocker.

**Comment by ibuziuk** [comment]
@mlabuda it is not "someone" thinking in jira - https://github.com/eclipse/che/blob/master/ide/che-core-ide-templates/src/main/resources/samples.json#L7

I have tested and for "java-default" stack, projectType is maven. Previously, there was a red cross on the project because no projectType was set

**Comment by mlabuda** [comment]
I am not sure why they have it that way there and precisely - what API endpoint they use to instantiate it.

Well, try it on yourself, that with this changes, if you are trying to create a project on java-default stack from e.g. https://github.com/mlabuda/vertx-with-che this application, you will get a project, which type is blank (you can easily try it through getting Che server API).

**Comment by ibuziuk** [comment]
@mlabuda ok, need to play with it and figure out what is wrong. Setting 'projectType' was suggested by the codenvy PM when I asked about red X issue on the slack

**Comment by mlabuda** [comment]
This is already done.
